In [1]:
import pandas as pd

In [2]:
# get all file paths in formatted_html folder
import os
from os import listdir
from os.path import isfile, join
mypath = os.getcwd() + '/formatted_html'
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]

In [55]:
test_file = onlyfiles[20]

In [9]:
print(test_file)

BIOS202_HUMAN ANATOMY OF THE THORAX.html

In [56]:
# use pandas to read html file to dataframes
tables = pd.read_html('formatted_html/' + test_file)

In [57]:
for i, table in enumerate(tables):
    print("TABLE " + str(i))
    print(table)

TABLE 0
                                                    0  \
0   Elliott Stollar Module Coordinator James Hartw...
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                           Org Unit:
7                                              Level:
8                                            Credits:
9                                        Module Code:
10                                        Deliveries:
11                                                  Â
12                                     In Programmes:

                                                    1   2
0   Metabolism 2025-26 Org Unit:Life Sciences NEWL... NaN
1                  Elliott Stollar Module Coordinator NaN
2                          James Hartwell Other Staff NaN
3                       Marco Sciacovelli Other Staff NaN
4                         Daniel Canniffe Other Staff NaN
5               Jeremy Paul Derrick External Examiner NaN
6                                   Life Sciences NEW NaN
7                                             Level 5 NaN
8                                                  15 NaN
9                                             BIOS212 NaN
10  Liverpool campus Â· Semester 2 Online Â· Semes... NaN
11                                                NaN NaN
12  Microbiology and Infection BSc (Hons) 2024-25 ... NaN
TABLE 1
    0                                      1
0 NaN     Elliott Stollar Module Coordinator
1 NaN             James Hartwell Other Staff
2 NaN          Marco Sciacovelli Other Staff
3 NaN            Daniel Canniffe Other Staff
4 NaN  Jeremy Paul Derrick External Examiner
TABLE 2
                0                                                  1
0       Org Unit:                                  Life Sciences NEW
1          Level:                                            Level 5
2        Credits:                                                 15
3    Module Code:                                            BIOS212
4     Deliveries:  Liverpool campus Â· Semester 2 Online Â· Semes...
5               Â                                                NaN
6  In Programmes:  Microbiology and Infection BSc (Hons) 2024-25 ...
TABLE 3
                                                    0  \
0                                             Details
1                                                 NaN
2                              Module TitleMetabolism
3                                        Module Title
4                               Short TitleMetabolism
..                                                ...
56                              Marked for RolloverNo
57                                Marked for Rollover
58  NotesNew module as part of programme revalidat...
59                                              Notes
60                                                NaN

                                                    1   2
0                                                 NaN NaN
1                                                 NaN NaN
2                                                 NaN NaN
3                                          Metabolism NaN
4                                                 NaN NaN
..                                                ...  ..
56                                                NaN NaN
57                                                 No NaN
58                                                NaN NaN
59  New module as part of programme revalidation. ... NaN
60                                                NaN NaN

[61 rows x 3 columns]
TABLE 4
              0           1   2
0  Module Title  Metabolism NaN
TABLE 5
             0           1   2
0  Short Title  Metabolism NaN
TABLE 6
             0        1   2
0  Module Code  BIOS212 NaN
TABLE 7
               0        1   2
0  Academic Year  2025-26 NaN
TABLE 8
          0                  1   2
0  Org Unit  Life Sciences NEW NaN
TABLE 9
                    0                        1   2
0  Delivery Locations  Liverpool campus Online NaN
TABLE 10
                  0           1   2
0  Delivery Periods  Semester 2 NaN
TABLE 11
         0   1   2
0  Credits  15 NaN
TABLE 12
       0        1   2
0  Level  Level 5 NaN
TABLE 13
                    0                1   2
0  Module Coordinator  Elliott Stollar NaN
TABLE 14
             0                                                 1   2
0  Other Staff  James Hartwell Marco Sciacovelli Daniel Canniffe NaN
TABLE 15
             0                                                  1   2
0  Assigned To  Matthew Wharton Elliott Stollar Life and Human... NaN
TABLE 16
        0              1   2
0  Status  Â Development NaN
TABLE 17
                  0                   1   2
0  Date of Approval  14 Sep 2023, 12:24 NaN
TABLE 18
                      0                    1   2
0  External Examiner(s)  Jeremy Paul Derrick NaN
TABLE 19
                                     0   1   2
0  Continuing Professional Development  No NaN
TABLE 20
                0    1   2
0  Maximum Places  200 NaN
TABLE 21
                   0            1   2
0  HESA Cost Centres  Biosciences NaN
TABLE 22
          0                                                  1   2
0  Overview  Students will explore the major animal and pla... NaN
TABLE 23
                  0                                                  1   2
0  Educational Aims  This module aims to â¢\tSupport students to d... NaN
TABLE 24
                           0  \
0  Marketing Module Synopsis

                                                   1   2
0  The module explores the major animal and plant... NaN
TABLE 25
                  0                                                  1   2
0  Outline Syllabus  Introduction to metabolism -\tReview of protei... NaN
TABLE 26
                               0  \
0  Teaching and Learning Methods

                                                   1   2
0  A typical week consists of 3 x 50 min interact... NaN
TABLE 27
                     0                                                  1   2
0  Assessment Strategy  The assessments reflect real-life and career-b... NaN
TABLE 28
                     0   1   2
0  Marked for Rollover  No NaN
TABLE 29
       0                                                  1   2
0  Notes  New module as part of programme revalidation. ... NaN
TABLE 30
  Unnamed: 0        Unnamed: 1  Unnamed: 2 Unnamed: 3
0          Â          Location      Period          Â
1          Â  Liverpool campus  Semester 2        NaN
2          Â            Online  Semester 2        NaN
TABLE 31
                   0                  1   \
0   Learning Outcomes  Learning Outcomes
1                 NaN                NaN
2                   Â          Reference
3                   Â                LO1
4                   Â                LO2
5                   Â                LO3
6                 NaN                NaN
7              Skills             Skills
8                 NaN                NaN
9                   Â          Reference
10                  Â                 S1
11                  Â                 S2
12                  Â                 S3
13                NaN                NaN

                                                   2                  3   \
0                                   Learning Outcomes  Learning Outcomes
1                                                 NaN                NaN
2                                             Outcome                  Â
3   Explain the purpose of the key metabolic pathw...                NaN
4   Explain the purpose of the key metabolic pathw...                NaN
5   Apply the principles of metabolism and regulat...                NaN
6                                                 NaN                NaN
7                                              Skills             Skills
8                                                 NaN                NaN
9                                             Outcome                  Â
10                              Written communication                NaN
11                Comprehend and use data effectively                NaN
12                                    Problem solving                NaN
13                                                NaN                NaN

                   4                  5                  6   \
0   Learning Outcomes  Learning Outcomes  Learning Outcomes
1                 NaN                NaN                NaN
2                 NaN                NaN                NaN
3                 NaN                NaN                NaN
4                 NaN                NaN                NaN
5                 NaN                NaN                NaN
6                 NaN                NaN                NaN
7              Skills             Skills             Skills
8                 NaN                NaN                NaN
9                 NaN                NaN                NaN
10                NaN                NaN                NaN
11                NaN                NaN                NaN
12                NaN                NaN                NaN
13                NaN                NaN                NaN

                   7                  8                  9   ...  \
0   Learning Outcomes  Learning Outcomes  Learning Outcomes  ...
1                 NaN                NaN                NaN  ...
2                 NaN                NaN                NaN  ...
3                 NaN                NaN                NaN  ...
4                 NaN                NaN                NaN  ...
5                 NaN                NaN                NaN  ...
6                 NaN                NaN                NaN  ...
7              Skills             Skills             Skills  ...
8                 NaN                NaN                NaN  ...
9                 NaN                NaN                NaN  ...
10                NaN                NaN                NaN  ...
11                NaN                NaN                NaN  ...
12                NaN                NaN                NaN  ...
13                NaN                NaN                NaN  ...

                   90                 91                 92  \
0   Learning Outcomes  Learning Outcomes  Learning Outcomes
1                 NaN                NaN                NaN
2                 NaN                NaN                NaN
3                 NaN                NaN                NaN
4                 NaN                NaN                NaN
5                 NaN                NaN                NaN
6                 NaN                NaN                NaN
7              Skills             Skills             Skills
8                 NaN                NaN                NaN
9                 NaN                NaN                NaN
10                NaN                NaN                NaN
11                NaN                NaN                NaN
12                NaN                NaN                NaN
13                NaN                NaN                NaN

                   93                 94                 95  \
0   Learning Outcomes  Learning Outcomes  Learning Outcomes
1                 NaN                NaN                NaN
2                 NaN                NaN                NaN
3                 NaN                NaN                NaN
4                 NaN                NaN                NaN
5                 NaN                NaN                NaN
6                 NaN                NaN                NaN
7              Skills             Skills             Skills
8                 NaN                NaN                NaN
9                 NaN                NaN                NaN
10                NaN                NaN                NaN
11                NaN                NaN                NaN
12                NaN                NaN                NaN
13                NaN                NaN                NaN

                   96                 97                 98                 99
0   Learning Outcomes  Learning Outcomes  Learning Outcomes  Learning Outcomes
1                 NaN                NaN                NaN                NaN
2                 NaN                NaN                NaN                NaN
3                 NaN                NaN                NaN                NaN
4                 NaN                NaN                NaN                NaN
5                 NaN                NaN                NaN                NaN
6                 NaN                NaN                NaN                NaN
7              Skills             Skills             Skills             Skills
8                 NaN                NaN                NaN                NaN
9                 NaN                NaN                NaN                NaN
10                NaN                NaN                NaN                NaN
11                NaN                NaN                NaN                NaN
12                NaN                NaN                NaN                NaN
13                NaN                NaN                NaN                NaN

[14 rows x 100 columns]
TABLE 32
          0          1                                            2   \
0  Summative  Summative                                    Summative
1        NaN        NaN                                          NaN
2          Â          Â                                        Title
3        NaN          Â  Written exam, open book, not managed by SAS
4        NaN          Â                                   Coursework
5        NaN        NaN                                          NaN

                     3              4                         5           6   \
0             Summative      Summative                 Summative   Summative
1                   NaN            NaN                       NaN         NaN
2            Deliveries  Weighting (%)  Learning Outcomes Tested  Group Work
3  Online Â· Semester 2           40 %                    LO1 S1          No
4                     Â           60 %      LO1 LO2 LO3 S1 S2 S3          No
5                   NaN            NaN                       NaN         NaN

                 7          8          9   ...         90         91  \
0         Summative  Summative  Summative  ...  Summative  Summative
1               NaN        NaN        NaN  ...        NaN        NaN
2  Final Assessment          Â        NaN  ...        NaN        NaN
3                No        NaN        NaN  ...        NaN        NaN
4               Yes        NaN        NaN  ...        NaN        NaN
5               NaN        NaN        NaN  ...        NaN        NaN

          92         93         94         95         96         97  \
0  Summative  Summative  Summative  Summative  Summative  Summative
1        NaN        NaN        NaN        NaN        NaN        NaN
2        NaN        NaN        NaN        NaN        NaN        NaN
3        NaN        NaN        NaN        NaN        NaN        NaN
4        NaN        NaN        NaN        NaN        NaN        NaN
5        NaN        NaN        NaN        NaN        NaN        NaN

          98         99
0  Summative  Summative
1        NaN        NaN
2        NaN        NaN
3        NaN        NaN
4        NaN        NaN
5        NaN        NaN

[6 rows x 100 columns]
TABLE 33
                                  0                                 1   \
0                  Independent Study                 Independent Study
1                                NaN                               NaN
2                                  Â                             Title
3                                  Â            Self-Directed Learning
4                                NaN                               NaN
5   Scheduled Directed Student Hours  Scheduled Directed Student Hours
6                                NaN                               NaN
7                                  Â                             Title
8                                  Â                           Lecture
9                                  Â                          Workshop
10                               NaN                               NaN

                                  2                                 3   \
0                  Independent Study                 Independent Study
1                                NaN                               NaN
2                              Hours                                 Â
3                                116                               NaN
4                                NaN                               NaN
5   Scheduled Directed Student Hours  Scheduled Directed Student Hours
6                                NaN                               NaN
7                              Hours                                 Â
8                                 30                               NaN
9                                  4                               NaN
10                               NaN                               NaN

                                  4                                 5   \
0                  Independent Study                 Independent Study
1                                NaN                               NaN
2                                NaN                               NaN
3                                NaN                               NaN
4                                NaN                               NaN
5   Scheduled Directed Student Hours  Scheduled Directed Student Hours
6                                NaN                               NaN
7                                NaN                               NaN
8                                NaN                               NaN
9                                NaN                               NaN
10                               NaN                               NaN

                                  6                                 7   \
0                  Independent Study                 Independent Study
1                                NaN                               NaN
2                                NaN                               NaN
3                                NaN                               NaN
4                                NaN                               NaN
5   Scheduled Directed Student Hours  Scheduled Directed Student Hours
6                                NaN                               NaN
7                                NaN                               NaN
8                                NaN                               NaN
9                                NaN                               NaN
10                               NaN                               NaN

                                  8                                 9   ...  \
0                  Independent Study                 Independent Study  ...
1                                NaN                               NaN  ...
2                                NaN                               NaN  ...
3                                NaN                               NaN  ...
4                                NaN                               NaN  ...
5   Scheduled Directed Student Hours  Scheduled Directed Student Hours  ...
6                                NaN                               NaN  ...
7                                NaN                               NaN  ...
8                                NaN                               NaN  ...
9                                NaN                               NaN  ...
10                               NaN                               NaN  ...


In [60]:
def get_learning_outcomes_table(tables):# find first table with "Learning Outcomes" at loc[0, 0]
    for i, table in enumerate(tables):
        try:
            if table.loc[0, 0] == "Learning Outcomes":
                print("TABLE " + str(i))
                print(table)
                break
        except:
            continue

In [46]:
module_short_name = tables[5].loc[0, 1]
module_code = tables[6].loc[0, 1]

outcomes = tables[32].loc[:, 1:2]

# remove rows with Nan in first column
outcomes = outcomes.dropna(subset=[1])

In [54]:
# use regex to find rows in LOS with column value
import re

lo_pattern = re.compile(r'LO\d{1,2}')
skill_pattern = re.compile(r'S\d{1,2}')
lo_rows = outcomes[outcomes[1].str.match(lo_pattern)]
skill_rows = outcomes[outcomes[1].str.match(skill_pattern)]

rows = []


for index, row in lo_rows.iterrows():
    rows.append({
        'module_short_name': module_short_name,
        'module_code': module_code,
        'type': "LO",
        'label': row[1],
        'description': row[2],
    })


    for index, row in skill_rows.iterrows():
        rows.append({
            'label': row[1],
            'description': row[2],
            'module_short_name': module_short_name,
            'module_code': module_code,
            'type': "SKILL",
        })

new_table = pd.DataFrame(rows)

print(new_table)

        module_short_name module_code   type label  \
0   Anatomy of the Thorax     BIOS202     LO   LO1
1   Anatomy of the Thorax     BIOS202  SKILL    S1
2   Anatomy of the Thorax     BIOS202  SKILL    S2
3   Anatomy of the Thorax     BIOS202  SKILL    S3
4   Anatomy of the Thorax     BIOS202     LO   LO2
5   Anatomy of the Thorax     BIOS202  SKILL    S1
6   Anatomy of the Thorax     BIOS202  SKILL    S2
7   Anatomy of the Thorax     BIOS202  SKILL    S3
8   Anatomy of the Thorax     BIOS202     LO   LO3
9   Anatomy of the Thorax     BIOS202  SKILL    S1
10  Anatomy of the Thorax     BIOS202  SKILL    S2
11  Anatomy of the Thorax     BIOS202  SKILL    S3
12  Anatomy of the Thorax     BIOS202     LO   LO4
13  Anatomy of the Thorax     BIOS202  SKILL    S1
14  Anatomy of the Thorax     BIOS202  SKILL    S2
15  Anatomy of the Thorax     BIOS202  SKILL    S3
16  Anatomy of the Thorax     BIOS202     LO   LO5
17  Anatomy of the Thorax     BIOS202  SKILL    S1
18  Anatomy of the Thorax     BIOS202  SKILL    S2
19  Anatomy of the Thorax     BIOS202  SKILL    S3
20  Anatomy of the Thorax     BIOS202     LO   LO6
21  Anatomy of the Thorax     BIOS202  SKILL    S1
22  Anatomy of the Thorax     BIOS202  SKILL    S2
23  Anatomy of the Thorax     BIOS202  SKILL    S3

                                          description
0   Describe relevant surface landmarks to guide t...
1   Communicate scientific knowledge confidently t...
2   Perform systematic examination of human cadave...
3   Show awareness of ethical and legal constraint...
4   Discuss the musculoskeletal components of the ...
5   Communicate scientific knowledge confidently t...
6   Perform systematic examination of human cadave...
7   Show awareness of ethical and legal constraint...
8   Explain the gross anatomy of major organs of t...
9   Communicate scientific knowledge confidently t...
10  Perform systematic examination of human cadave...
11  Show awareness of ethical and legal constraint...
12  Examine the topographic, functional and develo...
13  Communicate scientific knowledge confidently t...
14  Perform systematic examination of human cadave...
15  Show awareness of ethical and legal constraint...
16  Describe the significance of anatomical variat...
17  Communicate scientific knowledge confidently t...
18  Perform systematic examination of human cadave...
19  Show awareness of ethical and legal constraint...
20  Review the importance of anatomy in applicatio...
21  Communicate scientific knowledge confidently t...
22  Perform systematic examination of human cadave...
23  Show awareness of ethical and legal constraint...

In [50]:
skill_rows

     1                                                  2
13  S1  Communicate scientific knowledge confidently t...
14  S2  Perform systematic examination of human cadave...
15  S3  Show awareness of ethical and legal constraint...